### Testing GET PROVE
GET http://localhost:8000/api/
### Testing GET
GET http://localhost:8000/api/messages/sync

###Testing POST
POST http://localhost:8000/api/messages/new
Content-Type: application/json

{
    "message" : "Nuevo Mensaje #26",
    "name" : "Mario",
    "timestamp" : "Demo timestamp",
    "received" : true
}

###Testing POST false
POST http://localhost:8000/api/messages/new
Content-Type: application/json

{
    "message" : "Nuevo Mensaje #26",
    "name" : "Mario",
    "timestamp" : "Demo timestamp",
    "received" : false
}